#!/usr/bin/env ruby
require 'json'
require 'pathname'

pn = Pathname.new([__dir__, '..', 'src', 'manifest.json'].join('/'))

json = JSON.parse(File.open(pn).read)

version = json['version']

puts "Building BackerTracker version #{version}"

puts "Storing in dist BackerTracker Version #{version}"

destination_filename = Pathname.new([__dir__, '..', 'dist', "backertracker-extention-#{version}.zip"].join('/'))
puts `cd src && zip -r -FS #{destination_filename} * --exclude *.git*`
